title: Oluwafunsho Adaramaja
logo: Headshot.jpg
description: A data analyst with 3 years of experience, highly proficient with the use of data analytic tools like Excel, SQL and Power BI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
