title: Oluwafunsho Adaramaja
logo: Headshot.jpg
description: A data analyst with three years of experience in data analysis, I excel at working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making. I am proficient in Excel, SQL, Power BI, Python, Microsoft Office, and data manipulation. I combine problem-solving skills, attention to detail, and strong presentation abilities to deliver valuable analytical solutions.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
