title: Oluwafunsho Adaramaja
logo: Headshot.jpg
description: Analytical and detail-oriented Data Analyst with 8+ years of hands-on experience transforming complex, large-scale datasets into actionable business insights. Adept at working with diverse data sources and delivering high-impact analytics that support strategic decision-making. Highly proficient in SQL, Excel, Power BI, and Python for data modelling, visualisation, and statistical analysis. Skilled in presenting insights clearly and persuasively using PowerPoint, enabling both technical and non-technical stakeholders to drive results.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
